defmodule Taskboard.Repo.Migrations.AddTaskType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:template_tasks) do
      add :task_type, :text, null: false, default: "regular"
    end

    alter table(:project_tasks) do
      add :task_type, :text, null: false, default: "regular"
    end
  end

  def down do
    alter table(:project_tasks) do
      remove :task_type
    end

    alter table(:template_tasks) do
      remove :task_type
    end
  end
end
