defmodule Taskboard.Repo.Migrations.ProjectsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :reference_date, :date, null: false
      add :activated_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "draft"
      add :context_id, :uuid, null: false
      add :project_type_id, :uuid
      add :template_id, :uuid
    end

    create table(:project_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :allowed_context_types, {:array, :text}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:project_types, [:name], name: "project_types_unique_name_index")

    create table(:project_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :level, :bigint, null: false, default: 0
      add :position, :bigint, null: false, default: 1
      add :start_date, :date
      add :end_date, :date
      add :warning_date, :date
      add :completed_at, :utc_datetime_usec
      add :custom_field_values, :map, default: %{}
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "open"

      add :project_id,
          references(:projects,
            column: :id,
            name: "project_tasks_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :parent_id,
          references(:project_tasks,
            column: :id,
            name: "project_tasks_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :assigned_group_id,
          references(:groups,
            column: :id,
            name: "project_tasks_assigned_group_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :template_task_id,
          references(:template_tasks,
            column: :id,
            name: "project_tasks_template_task_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:project_task_dependencies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, default: "finish_to_start"
      add :lag_days, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :predecessor_id,
          references(:project_tasks,
            column: :id,
            name: "project_task_dependencies_predecessor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :successor_id,
          references(:project_tasks,
            column: :id,
            name: "project_task_dependencies_successor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:project_task_dependencies, [:predecessor_id, :successor_id],
             name: "project_task_dependencies_unique_dependency_index"
           )

    create table(:contexts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:projects) do
      modify :context_id,
             references(:contexts,
               column: :id,
               name: "projects_context_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :project_type_id,
             references(:project_types,
               column: :id,
               name: "projects_project_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :template_id,
             references(:templates,
               column: :id,
               name: "projects_template_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:contexts) do
      add :name, :text, null: false
      add :code, :text
      add :type, :text, null: false
      add :external_id, :text
      add :metadata, :map, default: %{}
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:contexts, [:type, :external_id],
             name: "contexts_unique_external_id_per_type_index"
           )
  end

  def down do
    drop_if_exists unique_index(:contexts, [:type, :external_id],
                     name: "contexts_unique_external_id_per_type_index"
                   )

    alter table(:contexts) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :metadata
      remove :external_id
      remove :type
      remove :code
      remove :name
    end

    drop constraint(:projects, "projects_context_id_fkey")

    drop constraint(:projects, "projects_project_type_id_fkey")

    drop constraint(:projects, "projects_template_id_fkey")

    alter table(:projects) do
      modify :template_id, :uuid
      modify :project_type_id, :uuid
      modify :context_id, :uuid
    end

    drop table(:contexts)

    drop constraint(:project_task_dependencies, "project_task_dependencies_predecessor_id_fkey")

    drop constraint(:project_task_dependencies, "project_task_dependencies_successor_id_fkey")

    drop_if_exists unique_index(:project_task_dependencies, [:predecessor_id, :successor_id],
                     name: "project_task_dependencies_unique_dependency_index"
                   )

    drop table(:project_task_dependencies)

    drop constraint(:project_tasks, "project_tasks_project_id_fkey")

    drop constraint(:project_tasks, "project_tasks_parent_id_fkey")

    drop constraint(:project_tasks, "project_tasks_assigned_group_id_fkey")

    drop constraint(:project_tasks, "project_tasks_template_task_id_fkey")

    drop table(:project_tasks)

    drop_if_exists unique_index(:project_types, [:name], name: "project_types_unique_name_index")

    drop table(:project_types)

    drop table(:projects)
  end
end
