defmodule Taskboard.Repo.Migrations.Milestones do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:template_tasks) do
      add :template_milestone_id, :uuid
    end

    create table(:template_milestones, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:template_tasks) do
      modify :template_milestone_id,
             references(:template_milestones,
               column: :id,
               name: "template_tasks_template_milestone_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:template_milestones) do
      add :name, :text, null: false
      add :description, :text
      add :due_offset_days, :bigint, null: false, default: 30
      add :warning_offset_days, :bigint, null: false, default: 7

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :template_id,
          references(:templates,
            column: :id,
            name: "template_milestones_template_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:project_tasks) do
      add :milestone_id, :uuid
    end

    create table(:milestones, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:project_tasks) do
      modify :milestone_id,
             references(:milestones,
               column: :id,
               name: "project_tasks_milestone_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:milestones) do
      add :name, :text, null: false
      add :description, :text
      add :due_date, :date, null: false
      add :warning_date, :date, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "milestones_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :template_milestone_id,
          references(:template_milestones,
            column: :id,
            name: "milestones_template_milestone_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:milestones, "milestones_project_id_fkey")

    drop constraint(:milestones, "milestones_template_milestone_id_fkey")

    alter table(:milestones) do
      remove :template_milestone_id
      remove :project_id
      remove :updated_at
      remove :inserted_at
      remove :warning_date
      remove :due_date
      remove :description
      remove :name
    end

    drop constraint(:project_tasks, "project_tasks_milestone_id_fkey")

    alter table(:project_tasks) do
      modify :milestone_id, :uuid
    end

    drop table(:milestones)

    alter table(:project_tasks) do
      remove :milestone_id
    end

    drop constraint(:template_milestones, "template_milestones_template_id_fkey")

    alter table(:template_milestones) do
      remove :template_id
      remove :updated_at
      remove :inserted_at
      remove :warning_offset_days
      remove :due_offset_days
      remove :description
      remove :name
    end

    drop constraint(:template_tasks, "template_tasks_template_milestone_id_fkey")

    alter table(:template_tasks) do
      modify :template_milestone_id, :uuid
    end

    drop table(:template_milestones)

    alter table(:template_tasks) do
      remove :template_milestone_id
    end
  end
end
