defmodule Taskboard.Repo.Migrations.TemplatesDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :family, :text
      add :reference_date_label, :text, default: "Referenzdatum"
      add :allowed_context_types, {:array, :text}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :status, :text, null: false, default: "draft"
    end

    create unique_index(:templates, [:name, :family],
             name: "templates_unique_name_per_family_index"
           )

    create table(:template_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :level, :bigint, null: false, default: 0
      add :position, :bigint, null: false, default: 1
      add :start_offset_days, :bigint, default: 0
      add :end_offset_days, :bigint, default: 7
      add :warning_offset_days, :bigint
      add :custom_field_defaults, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :template_id,
          references(:templates,
            column: :id,
            name: "template_tasks_template_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :parent_id,
          references(:template_tasks,
            column: :id,
            name: "template_tasks_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :assigned_group_id,
          references(:groups,
            column: :id,
            name: "template_tasks_assigned_group_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:template_tasks, [:template_id, :parent_id, :position],
             name: "template_tasks_unique_position_index"
           )

    create table(:template_task_dependencies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, default: "finish_to_start"
      add :lag_days, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :predecessor_id,
          references(:template_tasks,
            column: :id,
            name: "template_task_dependencies_predecessor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :successor_id,
          references(:template_tasks,
            column: :id,
            name: "template_task_dependencies_successor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:template_task_dependencies, [:predecessor_id, :successor_id],
             name: "template_task_dependencies_unique_dependency_index"
           )

    create table(:custom_field_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :label, :text, null: false
      add :field_type, :text, default: "text"
      add :required, :boolean, default: false
      add :position, :bigint, default: 1
      add :options, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :template_id,
          references(:templates,
            column: :id,
            name: "custom_field_definitions_template_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:custom_field_definitions, [:template_id, :name],
             name: "custom_field_definitions_unique_name_per_template_index"
           )
  end

  def down do
    drop constraint(:custom_field_definitions, "custom_field_definitions_template_id_fkey")

    drop_if_exists unique_index(:custom_field_definitions, [:template_id, :name],
                     name: "custom_field_definitions_unique_name_per_template_index"
                   )

    drop table(:custom_field_definitions)

    drop constraint(:template_task_dependencies, "template_task_dependencies_predecessor_id_fkey")

    drop constraint(:template_task_dependencies, "template_task_dependencies_successor_id_fkey")

    drop_if_exists unique_index(:template_task_dependencies, [:predecessor_id, :successor_id],
                     name: "template_task_dependencies_unique_dependency_index"
                   )

    drop table(:template_task_dependencies)

    drop constraint(:template_tasks, "template_tasks_template_id_fkey")

    drop constraint(:template_tasks, "template_tasks_parent_id_fkey")

    drop constraint(:template_tasks, "template_tasks_assigned_group_id_fkey")

    drop_if_exists unique_index(:template_tasks, [:template_id, :parent_id, :position],
                     name: "template_tasks_unique_position_index"
                   )

    drop table(:template_tasks)

    drop_if_exists unique_index(:templates, [:name, :family],
                     name: "templates_unique_name_per_family_index"
                   )

    drop table(:templates)
  end
end
