defmodule Taskboard.Repo.Migrations.AddAttachmentsAndComments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:comments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "comments_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :project_task_id,
          references(:project_tasks,
            column: :id,
            name: "comments_project_task_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :author_id,
          references(:users,
            column: :id,
            name: "comments_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :filename, :text, null: false
      add :content_type, :text, null: false
      add :size_bytes, :bigint, null: false
      add :storage_path, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "attachments_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :project_task_id,
          references(:project_tasks,
            column: :id,
            name: "attachments_project_task_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :uploaded_by_id,
          references(:users,
            column: :id,
            name: "attachments_uploaded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    execute("""
    ALTER TABLE attachments
      ADD CONSTRAINT exactly_one_parent CHECK (
        (project_id IS NOT NULL)::int + (project_task_id IS NOT NULL)::int = 1
      )
    """)

    execute("""
    ALTER TABLE comments
      ADD CONSTRAINT exactly_one_parent CHECK (
        (project_id IS NOT NULL)::int + (project_task_id IS NOT NULL)::int = 1
      )
    """)
  end

  def down do
    execute("""
    ALTER TABLE comments DROP CONSTRAINT IF EXISTS exactly_one_parent
    """)

    execute("""
    ALTER TABLE attachments DROP CONSTRAINT IF EXISTS exactly_one_parent
    """)

    drop constraint(:attachments, "attachments_project_id_fkey")

    drop constraint(:attachments, "attachments_project_task_id_fkey")

    drop constraint(:attachments, "attachments_uploaded_by_id_fkey")

    drop table(:attachments)

    drop constraint(:comments, "comments_project_id_fkey")

    drop constraint(:comments, "comments_project_task_id_fkey")

    drop constraint(:comments, "comments_author_id_fkey")

    drop table(:comments)
  end
end
